from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from tempfile import TemporaryDirectory
import logging

from angr import Project
from angr.analyses.cfg import CFGBase

from . import get_emu_cfg, get_fast_cfg
from .annotator import ColorSimprocedures, CommentsDataRef, CommentsAsm, ColorEdgesVex
from .content import NodeHead, NodeAsm
from .vis import Vis, XVis
from .output import DotOutput
from .source import CFGSource
from .transform import RemovePathTerminator, RemoveImports, RemoveSimProcedures, FilterNodes


def plot_cfg(cfg: CFGBase,
             fname: str,
             func_addr: int,
             format: str = "png",
             remove_imports: bool = True,
             remove_path_terminator: bool = True,
             remove_simprocedures: bool = False,
             comments: bool = True) -> None:

    logging.info("Start CFG plotting")

    vis = Vis()
    vis.set_source(CFGSource())
    if remove_path_terminator:
        vis.add_transformer(RemovePathTerminator())
    vis.add_content(NodeHead())
    vis.add_node_annotator(ColorSimprocedures())

    # asminst
    vis.add_content(NodeAsm())
    if comments:
        if cfg.sort == 'fast':
            vis.add_content_annotator(CommentsDataRef())
        else:
            vis.add_content_annotator(CommentsAsm())

    # color edges
    vis.add_edge_annotator(ColorEdgesVex())

    if remove_imports:
        vis.add_transformer(RemoveImports())
    if remove_simprocedures:
        vis.add_transformer(RemoveSimProcedures())

    vis.add_transformer(FilterNodes(node_filter=lambda node: node.obj.function_address == func_addr))
    vis.set_output(DotOutput(fname=fname, format=format))    
    vis.process(cfg)
    #return

    ######

    transformers = []
    if remove_path_terminator:
        transformers.append(RemovePathTerminator())
    if remove_imports:
        transformers.append(RemoveImports())
    if remove_simprocedures:
        transformers.append(RemoveSimProcedures())
    transformers.append(FilterNodes(node_filter=lambda node: node.obj.function_address == func_addr))

    annotators = []
    annotators.append(ColorSimprocedures())
    if comments:
        if cfg.sort == 'fast':
            annotators.append(CommentsDataRef())
        else:
            annotators.append(CommentsAsm())
    annotators.append(ColorEdgesVex())

    xvis = XVis(
        source=CFGSource(),
        output=DotOutput(fname=fname, format=format),
        transformers=transformers,
        contents=[NodeHead(), NodeAsm()],
        annotators=annotators
    )

    #xvis.process(cfg)


@lru_cache
def render_cfg(project: Project, func_addr: int, cfg_mode: str) -> str:
    """
    Render the control flow graph (CFG) of a specific function as an SVG image.

    This function builds the CFG of the project and verifies the presence of the function by address.
    It then uses a _CfgAdapter to prepare the CFG for visualization.
    A temporary directory is used to store the SVG output generated by plot_cfg.
    The SVG content is read, trimmed to remove any preceding data, and returned as a string.

    Args:
        project (angr.Project): The angr project containing the function.
        func_addr (int): The address of the function to visualize.
        fast_mode (bool): Method for getting the function CFG.

    Returns:
        str: The SVG content representing the function's CFG.

    Raises:
        KeyError: If the function address is not found in the CFG.
        RuntimeError: If the CFG graph is not available for visualization.
    """
    # extract nexworkx digraph for the function
    if cfg_mode == "fast":
        logging.info(f"Getting fast CFG for function {func_addr:#x}")
        cfg = get_fast_cfg(project)
    else:
        logging.info(f"Getting emulated CFG for function {func_addr:#x}")
        cfg = get_emu_cfg(project, func_addr)

    # check if function is found in CFG
    if not cfg.functions.get(func_addr):
        raise KeyError(f"Function {func_addr:#x} not found in CFG")

    # Create SVG graph in temporal file
    with TemporaryDirectory() as tmp_dir:
        output_base = Path(tmp_dir) / f"cfg_{func_addr:x}"
        plot_cfg(
            cfg,
            str(output_base),
            func_addr=func_addr,
            format="svg",
            remove_imports=True,
            remove_path_terminator=False,
            remove_simprocedures=False,
            comments=True
        )
        svg_path = output_base.with_suffix(".svg")
        svg = svg_path.read_text(encoding="utf-8")

    svg_start = svg.find("<svg")
    if svg_start != -1:
        svg = svg[svg_start:]
    return svg
