from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from tempfile import TemporaryDirectory

from angr import Project
from angr.analyses.cfg import CFGBase
from loguru import logger

from bingraph.helpers import get_settings  #, serialize_function, serialize_function_summary
from . import get_cfg
from .annotators import ColorSimprocedures, CommentsDataRef, ColorEdgesVex
from .contents import NodeHead, NodeAsm
from .vis import Vis
from .outputs import DotOutput
from .sources import CFGSource


def plot_cfg(cfg: CFGBase,
             fname: str,
             func_addr: int,
             format: str,
             comments: bool = True) -> None:

    logger.info(f"Start CFG plotting function at {hex(func_addr)} as {format}")

    annotators = []
    annotators.append(ColorSimprocedures())
    if comments:
        annotators.append(CommentsDataRef())
    annotators.append(ColorEdgesVex())

    vis = Vis(
        source=CFGSource(func_addr=func_addr),
        output=DotOutput(fname=fname, format=format),
        transformers=[],
        contents=[NodeHead(), NodeAsm()],
        annotators=annotators
    )

    vis.process(cfg)


@lru_cache
def render_cfg(project: Project, func_addr: int, cfg_mode: str, format: str = "svg") -> str:
    """
    Render the control flow graph (CFG) of a specific function as an SVG image.

    This function builds the CFG of the project and verifies the presence of the function by address.
    It then uses a _CfgAdapter to prepare the CFG for visualization.
    A temporary directory is used to store the SVG output generated by plot_cfg.
    The SVG content is read, trimmed to remove any preceding data, and returned as a string.

    Args:
        project (angr.Project): The angr project containing the function.
        func_addr (int): The address of the function to visualize.
        fast_mode (bool): Method for getting the function CFG.

    Returns:
        str: The SVG content representing the function's CFG.

    Raises:
        KeyError: If the function address is not found in the CFG.
        RuntimeError: If the CFG graph is not available for visualization.
    """
    # extract nexworkx digraph for the function
    cfg = get_cfg(project, func_addr, cfg_mode)
    settings = get_settings()

    # check if function is found in CFG
    function = cfg.functions.get(func_addr)
    if not function:
        raise KeyError(f"Function {func_addr:#x} not found in CFG")

    #logger.info(serialize_function_summary(function))
    #logger.info(serialize_function(function))

    # Create SVG graph in temporal file
    with TemporaryDirectory() as tmp_dir:
        output_base = Path(tmp_dir) / f"cfg_{func_addr:x}"
        plot_cfg(
            cfg,
            str(output_base),
            func_addr=func_addr,
            format=format,
            comments=settings.comments
        )
        output_path = output_base.with_suffix(f".{format}")
        output = output_path.read_text(encoding="utf-8")

    #svg_start = output.find("<svg")
    #if svg_start != -1:
    #    output = output[svg_start:]
    return output
